<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.2.1</Version>
    <Authors>Dotcom Cloud Operations</Authors>
    <PackageOutputPath>$(MSBuildThisFileDirectory)nupkgs/</PackageOutputPath>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
  </ItemGroup>
</Project>
